app_name: JCheng
version: 1.1.1
version_code: 111

flutter:
  dependencies:
    flutter:
      sdk: flutter
    # 新增主流稳定版扫码插件，底层ZXing，Dart原生解码
    mobile_scanner: ^4.0.1

android:
  package: com.flet.jcheng_erp
  label: JCheng
  build_type: release

  permissions:
    - android.permission.INTERNET
    - android.permission.ACCESS_NETWORK_STATE
    - android.permission.CAMERA
    # Android13+ 图片、视频媒体权限
    - android.permission.READ_MEDIA_IMAGES
    - android.permission.READ_MEDIA_VIDEO
    # Android12及以下兼容存储权限
    - name: android.permission.READ_EXTERNAL_STORAGE
      maxSdkVersion: 32
    - name: android.permission.WRITE_EXTERNAL_STORAGE
      maxSdkVersion: 32
    # 前台定位权限
    - android.permission.ACCESS_FINE_LOCATION
    - android.permission.ACCESS_COARSE_LOCATION

  features:
    - name: android.hardware.camera
      required: false
    - name: android.hardware.camera.autofocus
      required: false
    - name: android.hardware.location
      required: false
    - name: android.hardware.location.gps
      required: false
    - name: android.hardware.location.network
      required: false

  application:
    requestLegacyExternalStorage: true
    android:preserveLegacyExternalStorage: true
    android:exported: true
    # mobile_scanner 需要开启相机硬件特性必选
    meta_data:
      - name: android.hardware.camera.autofocus
        value: true
